### PR TITLE
MikroTik Support

### PR DESCRIPTION
**Pull request by cdavid14**
Some functions for MikroTik support added.

### CODE REVIEW

**Comment by job** [comment]
@cdavid14 can you ensure that your use of tabs / spaces is consistent with the rest of the code? I see in at least one spot that spaces were used where tabs would've been better.

Can you make the readme shorter?

**Comment by cdavid14** [comment]
@job thanks for the tips, i've fixed it at #eff95ce , maybe the indent problem was my text editor at the time i've submitted, if you have more comments please tell-me and i will review :smile:

**Comment by job** [comment]
@cdavid14 can you squash your commits into a single commit?

@snar can you take a look and merge? this looks good to me

**Comment by cdavid14** [comment]
Done @job , waiting for @snar opinion about the pull request :smile:

**Comment by maximiliandallmair** [comment]
please PULL

**Comment by ffrediani** [comment]
Hello folks. What is pending for this commit to be pulled ? That's a welcome feature.

**Comment by cdavid14** [comment]
@job  you can merge this PR ?

**Comment by job** [comment]
@cdavid14 I'm sorry but I don't have the github permissions to do so

**Comment by cdavid14** [comment]
@snar The project is dead?

**Comment by snar** [comment]
The idea that Mikrotik will be supported is dead. Let me bury it so it will not stink anymore.

**Comment by cdavid14** [comment]
Thanks for answer @snar , a year stinking its a lot of time haha

**Comment by ffrediani** [comment]
I might be wrong, but the code was ready to be pulled merged to bpgq3 for Mikrotik support and worked fine. What actually happened that this didn't happen ?

**Comment by fischerdouglas** [comment]
Hey @snar, I used to be a consultant to Small ISPs here in Brazil.

I'm also not a fan of Mikrotik...
But I have to Deal with at least one of It every two or three days.

Beyond the poor quality code of RouterOS, thw worst part os the majority of the users of ir does not have the needed skiils to tô some good filtering in BGP, (not on BGP, not o Cisco, not on Juniper).

So, what we are trying to do is, based on the orientations of @Job about dynamic prefix-lists based on IRR, and create automated tools to those limited guys to they use and, as possible, do not create problems to every one else on the Internet.

Here in Brazil, unfortunately se have something like 6000 ASNs using Mikrotik as BGP engine (😭😭😭)

Tô improve the security of the internet routing, could you please reconsider your position?

**Comment by snar** [comment]
Guys, this pull request is closed. Period.

PS: have to admit that I was stupid enough for not closing it in 
the same day I saw the code.

**Comment by ffrediani** [comment]
@snar I must agree with @fischerdouglas 
If the code is functional and adds a functionality to the software which is useful to others using it that's what matters, not your personal feelings about some specific vendor.
Otherwise why do you publish the software as open source and put its opened to receive contributions ?

Mikrotik is a reality and largely used in several countries and organizations using it have normally other issues to deal with. Making them to have yet another issue, which is to do manual filtering because of the lack of tool which is ready to be used is the same as making something bad not only for them but for Internet ecosystem that may be impacted by lack of proper filter.

Again, what needs to be analysed is if the code is functional and functionality useful to others, not if you like or not of that vendor. This only adds another vendor among others already present.
Otherwise just remove the code from public access and keep it to yourself as your personal toy as it doesn't make sense to make decisions to refuse functional code in such manner.

**Comment by jkroonza** [comment]
Hi,

I fully agree with @ffrediani and @fischerdouglas.

Having said that, it's plain @snar feels differently, and this is his project.  You don't like it.  fork it or live with it.

For those that really need MT support as it stands, this can be done with -F:

`$ bgpq3 -F "/routing filter add action=accept chain=\"%N-V4\" prefix=%n/%l prefix-length=0-24\n" -4 AS327767 -l ULTIMATE-LINUX`
`/routing filter add action=accept chain="ULTIMATE-LINUX-V4" prefix=154.73.32.0/22 prefix-length=0-24`
`/routing filter add action=accept chain="ULTIMATE-LINUX-V4" prefix=165.16.200.0/21 prefix-length=0-24`

Somewhat messy, but it works.

**Comment by ffrediani** [comment]
Hello @jkroonza this has already been done and bgpq4 (https://github.com/bgp/bgpq4) has been forked and has Mikrotik support fine.
But thanks for the tip. It should work for those who still use bgpq3

**Pull request closed without merging**
